### ISSUE TITLE
Show total test count

### ISSUE THREAD

**Issue by kentcdodds** [dgarlitt/karma-nyan-reporter#11]
It would be nice if the numbers on the left showed how many total tests there are so I get some idea of the progress of the test suite. Any way we could include this?

**Comment by dgarlitt** [comment]
I started to mark this as an enhancement, however I'm pretty sure that karma doesn't provide a count of the tests prior to running. Therefore the reporter would have no way of knowing how many tests are in the suite. Hopefully my suspicions will be proven wrong, but I am a little bit pessimistic at this point. I'll look into it further and post some feedback.

**Comment by kentcdodds** [comment]
Thanks for looking into it! The progress reporter does it, but it's built-in and may be using internal apis I suppose...

**Comment by dgarlitt** [comment]
Thanks, that helped a bunch. I see where it is getting the number from, so it appears to be doable. I will see about including this in an upcoming release.

**Comment by dgarlitt** [comment]
This feature was added in [release 0.1.00](https://github.com/dgarlitt/karma-nyan-reporter/releases/tag/v0.1.00) and is available now via [npm](https://www.npmjs.com/package/karma-nyan-reporter).

**Comment by kentcdodds** [comment]
Awesome! Works great! Thank you!
