### ISSUE TITLE
Nyan reporter output is strange when there is uncaught exception outside tests

### ISSUE THREAD

**Issue by kibin** [dgarlitt/karma-nyan-reporter#17]
When there is an error somewhere outside tests nyan reporter is behaving weird. When I run tests using standard dots reporter I see error and logs:

<img width="1278" alt="screen shot 2015-10-05 at 12 38 36 pm" src="https://cloud.githubusercontent.com/assets/1782569/10277420/70354f82-6b5e-11e5-9d0a-1f5f2685c640.png">

And I can say that something wrong and even see the exception.
But when I try nyan reporter I see this:

<img width="1003" alt="screen shot 2015-10-05 at 12 39 38 pm" src="https://cloud.githubusercontent.com/assets/1782569/10277442/8fa5c090-6b5e-11e5-9a83-b5c10d1d57dc.png">

No logs, no errors, cursor in the strange place.
And if I save a couple of times the output gets totally corrupted:

<img width="1280" alt="screen shot 2015-10-05 at 12 40 09 pm" src="https://cloud.githubusercontent.com/assets/1782569/10277453/9f4d6868-6b5e-11e5-81a7-c7dd94e3a5c8.png">

**Comment by Fatxx** [comment]
+1
