### ISSUE TITLE
Nyan output is strange on Mac OS El Capitan

### ISSUE THREAD

**Issue by carloshpds** [dgarlitt/karma-nyan-reporter#19]
The output does not show the resume of tests and the next writing of any process overrides the nyan output
![screen shot 2015-11-03 at 10 58 06](https://cloud.githubusercontent.com/assets/2482989/10908698/ae04a57e-821a-11e5-8c4e-ca8f63fb8b56.jpg)

**Comment by dgarlitt** [comment]
@carloshpds Could you give some more context on what was happening, configuration and how it was being run or any other information so I can try and figure out what may have caused this?

Thanks,
Daniel

**Comment by carloshpds** [comment]
Sorry, i don't know exactly what was happening. 
But could be my fault, my conclusion for this: The way that i was running karma made it.

I updated karma to v0.13 (it was v0.12) and implemented the new syntax for karma server.

from:
```
karma.server.start(options, function(){done() });
```

to :
```
var server = new karma.Server(options, function(){ done() });
server.start();
```

This way the output instability has gone.

**Comment by dgarlitt** [comment]
@carloshpds Thanks for looking into it and closing the issue!

**Comment by carloshpds** [comment]
:+1:
