### ISSUE TITLE
Issue with display when run through 'Task Runner Explorer' in VS

### ISSUE THREAD

**Issue by ste2425** [dgarlitt/karma-nyan-reporter#22]
When being run through Visual Studio's Task Runner Explorer for Node the output appears broken. Instead of moving from left to right, each 'step' is re-rendered on the line below.

Running the same through CMD or GitBash and it renders correctly.

Task runner:
![image](https://cloud.githubusercontent.com/assets/8177767/19066312/956a0276-8a10-11e6-8ab6-b40861fba4b0.png)

GitBash:
![image](https://cloud.githubusercontent.com/assets/8177767/19066329/b36dccf8-8a10-11e6-8192-aeaf50aa3530.png)

This is using: V0.2.4

**Comment by dgarlitt** [comment]
@ste2425 I appreciate the feedback, however I don't have a setup for debugging Windows behaviors. This is the first issue opened relating to this scenario. I will leave it open for a bit to see if you or someone else with a similar setup wants to try and debug the issue. If a clean/simple cross-compatible solution can be arrived at, I will be happy to accept the pull request.

If the issue remains untouched for too much longer, I will be closing it. In the meantime, you can use `renderOnRunCompleteOnly: true` in your karma config file to have the output rendered only after all tests have finished (it's not as fun to watch, though).

**Comment by whyboris** [comment]
I strongly suspect that `renderOnRunCompleteOnly: true` is an adequate solution to the problem.

Issue seems not to happen on `VS Code 1.12.2` (running MacOS Sierra) -- animation shows correctly. Unsure about Visual Studio's `Task Runner Explorer` -- it looks like it's not been updated since early 2015.
