### ISSUE TITLE
Total tests count is different from other reporters

### ISSUE THREAD

**Issue by idiotWu** [dgarlitt/karma-nyan-reporter#23]
When I run tests in multiple browsers, it seems nyan reporter will only count total tests from one test suite:

![wx20170104-150939](https://cloud.githubusercontent.com/assets/6022672/21633139/e3ba7c22-d28f-11e6-9da6-1abe69daa990.png)

![wx20170104-150956](https://cloud.githubusercontent.com/assets/6022672/21633142/e67b838e-d28f-11e6-85c1-c39093e55fe5.png)

Notice that the total count and passed count stay the same. And if I use the `mocha-reporter`, I will actually get a total count at `64`:

![wx20170104-151149](https://cloud.githubusercontent.com/assets/6022672/21633179/370a7efe-d290-11e6-9da8-c27013a2ebdf.png)

**Comment by idiotWu** [comment]
I got a solution to this issue, a PR will be sent soon 😺

**Comment by dgarlitt** [comment]
@idiotWu Thanks for the PR, looks good. Will merge and create a release.

**Comment by dgarlitt** [comment]
@idiotWu Your changes have been merged and [published to npm in the latest release](https://www.npmjs.com/package/karma-nyan-reporter)
